// ══════════════════════════════════════════════════
// CATÁLOGO DE PRODUCTOS — Silver Cow Ambato
// Para agregar un producto: copia un objeto {} y llena los campos
// estado: "disponible" | "agotado" | "pedido"
// esPedido: true (bajo pedido) | false (disponible/agotado)
// ══════════════════════════════════════════════════

const CATALOGO = {

  // ── PULSERAS ──
  pulseras: [
    { estado: 'disponible', img: 'pulseras/pulsera_1.jpg', nombre: "Pulsera Clásica", desc: "[P-PL-136] Diseño elegante de cadena fina, ideal para uso diario.", precio: 25.0, esPedido: false },
    { estado: 'disponible', img: 'pulseras/pulsera_2.jpg', nombre: "Pulsera Cristal", desc: "[P-PL-291] Pulsera plata ley 925 cristales blancos", precio: 20.0, esPedido: false },
    { estado: 'pedido', img: 'pulseras/pulsera_3.jpg', nombre: "Pulsera Clasica N°2", desc: "[P-PL-284] Pulsera en plata tejido barbabda recta 21 cm.", precio: 60.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_4.jpg', nombre: "Pulsera Ala Cristal", desc: "[P-PL-200] Pulsera en plata ley 925 dije ala cristal.", precio: 18.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_5.jpg', nombre: "Pulsera rígida N°1", desc: "[P-PL-205] Pulsera rígida tres mariposas.", precio: 60.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_6.jpg', nombre: "Pulsera rígida N°2", desc: "[P-PL-206] Pulsera rígida una mariposa.", precio: 55.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_7.jpg', nombre: "Pulsera semi-rígida", desc: "[P-PL-105] Pulsera en plata quemada 925 guaya y hoja", precio: 37.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_8.jpg', nombre: "Pulsera plata Búho", desc: "[P-PL-176] Pulsera plata ley 925 con cristales violetas y encantos de búho", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_9.jpg', nombre: "Pulsera ajustabe", desc: "[P-PL-322] Pulsera en plata ley 925 ajustable hilo rojo tejido 7 balines", precio: 17.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_10.jpg', nombre: "Pulsera ajustabe", desc: "[P-PL-327] Pulsera en plata ley 925 cordón ajustable negros balines", precio: 16.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_11.jpg', nombre: "Pulsera eslabones", desc: "[P-PL-104] Pulsera en plata 925 eslabones caña bolas flor y palo azul rojo", precio: 60.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_12.jpg', nombre: "Pulsera medalla", desc: "[P-PL-163] Pulsera en plata ley 925 bolas medalla san benito", precio: 55.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_13.jpg', nombre: "Pulsera cordón ajustable beige", desc: "[P-PL-330] Pulsera en plata ley 925 cordón ajustable beige balines de plata bola ágata hielo.", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_14.jpg', nombre: "Pulsera cordón ajustable blanco", desc: "[P-PL-321] Pulsera en plata ley 925 cordón ajustable blanco balines bola microcirconia cubica azul rodinado.", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_15.jpg', nombre: "Pulsera ala ángel", desc: "[P-PL-250] Pulsera plata ley 925 dije ala ángel.", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_16.jpg', nombre: "Pulsera ala ángel", desc: "[P-PL-288] Pulsera en plata ley 925 esclava bebé mariquita esmaltado 12cm con extensión.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_17.jpg', nombre: "Pulsera circones rojos", desc: "[P-PL-173] Pulseras plata quemada ley 925 circones rojos.", precio: 38.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_18.jpg', nombre: "Pulsera marquesita ovalo N° 1", desc: "[P-PL-304] Pulsera plata quemada ley 925 marquesita ovalo circones violeta.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_19.jpg', nombre: "Pulsera marquesita flor", desc: "[P-PL-303] Pulsera plata quemada ley 925 marquesita flor circones verdes.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_20.jpg', nombre: "Pulsera ovalo N° 1", desc: "[P-PL-301] Pulsera plata quemada ley 925 marquesita ovalo cristal azul.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_21.jpg', nombre: "Pulsera ovalo N° 2", desc: "[P-PL-299] Pulsera plata quemada ley 925 marquesita ovalo cristal verdes.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_22.jpg', nombre: "Pulsera marquesita círculo", desc: "[P-PL-298] Pulsera plata quemada ley 925 marquesita círculo cristales violeta.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_23.jpg', nombre: "Pulsera marquesita ovalo N° 2", desc: "[P-PL-295] Pulsera plata quemada ley 925 marquesita ovalo circones negros.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_24.jpg', nombre: "Pulsera marquesita circones", desc: "[P-PL-283] Pulsera en plata ley 925 plata quemada marquesita circones negros.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_25.jpg', nombre: "Pulsera gotas circones", desc: "[P-PL-172] Pulseras plata quemada ley 925 gotas circones magenta.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'pulseras/pulsera_26.jpg', nombre: "Pulsera marquesita ramitas", desc: "[P-PL-302] Pulsera plata quemada ley 925 marquesita ramitas circones rojos.", precio: 40.0, esPedido: true },
  ],

  // ── ANILLOS ──
  anillos: [
    { estado: 'pedido', img: 'anillos/anillo_1.jpg', nombre: "Anillo Ajustable N° 1", desc: "[P-AN-368] Anillo en plata ley 925 corazón estetoscopio ajustable", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_2.jpg', nombre: "Anillo Ajustable N° 2", desc: "[P-AN-107] Anillo plata 925 estilo ajustable media luna", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_3.jpg', nombre: "Anillo circón", desc: "[P-AN-215] Anillo en Plata ley 925 circón color magenta", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_4.jpg', nombre: "Anillo circón", desc: "[P-AN-210] Anillo en Plata ley 925 circón blanco tipo solitario", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_5.jpg', nombre: "Anillo pisargolla", desc: "[P-AN-108] Anillo en plata ley 925 pisargolla set x 2 - talla 7 \"Pregunte por más información\"", precio: 50.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_6.jpg', nombre: "Anillo alianza N° 1", desc: "[P-AN-223] Anillo plata 925 alianza matrimonio lisas 6mm", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_7.jpg', nombre: "Anillo alianza N° 2", desc: "[P-AN-222] Anillo plata 925 alianza matrimonio lisas 4mm x unidad", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_8.jpg', nombre: "Anillo alianza N° 3", desc: "[P-AN-196] Anillo plata 925 alianza x2 circon love", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_9.jpg', nombre: "Anillo y oro", desc: "[P-AN-199] Anillo plata 925 y oro dos lineas doradas", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_10.jpg', nombre: "Anillo esmeralda N° 1", desc: "[P-AN-242] Anillo edición especial esmeralda autentica plata 925", precio: 165.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_11.jpg', nombre: "Anillo esmeralda N° 2", desc: "[P-AN-243] Anillo edición especial esmeralda autentica plata 925", precio: 145.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_12.jpg', nombre: "Anillo esmeralda N° 3", desc: "[P-AN-244] Anillo edición especial esmeralda autentica plata 925", precio: 135.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_13.jpg', nombre: "Anillo laminado", desc: "[P-AN-385] Anillo plata ley 925 y laminado oro - talla 8", precio: 25.0, esPedido: true },
    { estado: 'disponible', img: 'anillos/anillo_14.jpg', nombre: "Anillo Ajustable N° 3", desc: "[P-AN-357] Anillo en plata ley 925 flor circon ajustable", precio: 20.0, esPedido: false },
    { estado: 'pedido', img: 'anillos/anillo_16.jpg', nombre: "Anillo triangulo", desc: "[P-AN-168] Anillo plata 925 hilo fino triangulo.", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_17.jpg', nombre: "Anillo ojo", desc: "[P-AN-167] Anillo plata 925 hilo fino ojo pestañas.", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_18.jpg', nombre: "Anillo ajustabel puntos", desc: "[P-AN-174] Anillo plata 925 ajustable puntos circones.", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_19.jpg', nombre: "Anillo infinito", desc: "[P-AN-152] Anillo plata 925 infinito plata quemada.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_20.jpg', nombre: "Anillo van cleef corazón", desc: "[P-AN-240] Anillo plata ley 925 van cleef corazón color surtido.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_21.jpg', nombre: "Anillo colgante circon", desc: "[P-AN-141] Anillo plata 925 colgante circon cuadrado.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_22.jpg', nombre: "Anillo tejido", desc: "[P-AN-179] Anillo plata 925 tejido tipo cinturón.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_23.jpg', nombre: "Anillo solitario", desc: "[P-AN-171] Anillo plata ley 925 tipo solitario circón azul.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_24.jpg', nombre: "Anillo circón redondo", desc: "[P-AN-151] Anillo plata ley 925 circón redondo verde.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_25.jpg', nombre: "Anillo silueta corazón", desc: "[P-AN-369] Anillo en plata ley 925 silueta corazón.", precio: 18.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_26.jpg', nombre: "Anillo corazones dobles", desc: "[P-AN-356] Anillo en plata ley 925 corazones dobles.", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_27.jpg', nombre: "Anillo trenzado", desc: "[P-AN-233] Anillo en plata ley 925 trenzado talla 8.", precio: 21.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_28.jpg', nombre: "Anillo lazo microcircones", desc: "[P-AN-156] Anillo plata 925 lazo microcircones de color.", precio: 20.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_29.jpg', nombre: "Anillo engranaje", desc: "[P-AN-160] Anillo plata 925 engranaje microcircones blancos.", precio: 21.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_30.jpg', nombre: "Anillo circulo", desc: "[P-AN-358] Anillo en plata ley 925 circulo microcircones regulable.", precio: 21.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_31.jpg', nombre: "Anillo aro", desc: "[P-AN-350] Anillo en plata ley 925 aro diamantado.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_32.jpg', nombre: "Anillo thai circulo", desc: "[P-AN-219] Anillo en plata ley 925 thai circulo cristales baguette.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_33.jpg', nombre: "Anillo puntos circones", desc: "[P-AN-146] Anillo plata 925 puntos circones redondos azules.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_34.jpg', nombre: "Anillo thai osito", desc: "[P-AN-212] Anillo en plata ley 925 thai osito color surtido.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_35.jpg', nombre: "Anillo tipo bola", desc: "[P-AN-248] Anillo plata ley 925 tipo solitario bola humor.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_36.jpg', nombre: "Anillo barra lisa", desc: "[P-AN-227] Anillo plata ley 925 barra lisa microcircones laterales.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_37.jpg', nombre: "Anillo alas libélula", desc: "[P-AN-225] Anillo plata ley 925 alas libélula.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_38.jpg', nombre: "Anillo mariposa esmaltada", desc: "[P-AN-211] Anillo plata ley 925 mariposa esmaltada.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_39.jpg', nombre: "Anillo flor circon", desc: "[P-AN-138] Anillo plata 925 flor circon color.", precio: 25.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_40.jpg', nombre: "Anillo mariposas doble", desc: "[P-AN-246] Anillo en Plata ley 925 mariposas doble esmaltadas.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_41.jpg', nombre: "Anillo thai microcirconia", desc: "[P-AN-205] Anillo en plata 925 thai microcirconia surtido.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_42.jpg', nombre: "Anillo solitario cuadrado", desc: "[P-AN-366] Anillo en plata ley 925 tipo solitario circón verde / azul.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_43.jpg', nombre: "Anillo dos rositas", desc: "[P-AN-379] Anillo en plata ley 925 dos rositas microcircones blanco / color.", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_44.jpg', nombre: "Anillo puntos circones blancos", desc: "[P-AN-157] Anillo plata 925 puntos circones blancos", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_45.jpg', nombre: "Anillo circón modelo 2", desc: "[P-AN-153] Anillo plata ley 925 tipo solitario circón modelo 2.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_46.jpg', nombre: "Anillo círculo baguette", desc: "[P-AN-257] Anillo plata ley 925 círculo cristales baguette.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_47.jpg', nombre: "Anillo cristal negro", desc: "[P-AN-254] Anillo plata ley 925 cristal negro gota.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_48.jpg', nombre: "Anillo cristal ovalado", desc: "[P-AN-253] Anillo plata ley 925 cristal verde ovalado.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_49.jpg', nombre: "Anillo cristal redondo", desc: "[P-AN-252] Anillo plata ley 925 cristal redondo magenta.", precio: 25.5, esPedido: true },
    { estado: 'pedido', img: 'anillos/anillo_50.jpg', nombre: "Anillo ovalo microcircones", desc: "[P-AN-251] Anillo plata ley 925 ovalo microcircones blancos.", precio: 25.5, esPedido: true },
  ],

  // ── ARETES ──
  aretes: [
    { estado: 'disponible', img: 'aretes/arete_1.jpg', nombre: "Argolla huggie N° 1", desc: "[P-AR-157] Argolla huggie plata 925 (b.rodio) cristal baguette 1.4 cm.", precio: 23.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_2.jpg', nombre: "Aretes Topo N° 1", desc: "[P-AR-237] Arretes Topo plata 925 circón verde cuadrado n2,5.", precio: 5.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_3.jpg', nombre: "Aretes Topo N° 2", desc: "[P-AR-247] Topo plata 925 liviano patitos", precio: 7.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_4.jpg', nombre: "Aretes Topo N° 3", desc: "[P-AR-351] Topo en plata ley 925 cristal redondo blanco #5", precio: 7.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_5.jpg', nombre: "Aretes Topo N° 4", desc: "[P-AR-226] Topo en plata ley 925 cristal redondo blanco #5", precio: 5.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_6.jpg', nombre: "Aretes Gota", desc: "[P-AR-569] Aretes de plata ley 925 Cristal Gota magenta", precio: 18.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_7.jpg', nombre: "Argolla Lisa N° 1", desc: "[P-AR-293] Argolla plata 925 lisa 1,2cm", precio: 5.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_8.jpg', nombre: "Aretes Topo N° 5", desc: "[P-AR-238] Arretes Topo plata 925 circón verde cuadrado n6.", precio: 7.0, esPedido: false },
    { estado: 'disponible', img: 'aretes/arete_9.jpg', nombre: "Aretes Topo N° 6", desc: "[P-AR-552] Arretes Topo plata 925 mini corazones.", precio: 7.0, esPedido: false },
    { estado: 'pedido', img: 'aretes/arete_10.jpg', nombre: "Argolla huggie N° 2", desc: "[P-AR-183] Argolla huggie plata lisa 1.5 cm", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_11.jpg', nombre: "Argolla", desc: "[P-AR-356] Argollas en plata ley 925 lisa tipo hilo 4.5 cm", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_12.jpg', nombre: "Argolla lisa N° 2", desc: "[P-AR-198] Arete argolla lisa tubular 2,6cm plata 925", precio: 30.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_13.jpg', nombre: "Argolla lisa N° 3", desc: "[P-AR-295] Argolla plata 925 lisa gancho anzuelo 1,2cm", precio: 6.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_14.jpg', nombre: "Argolla lisa N° 4", desc: "[P-AR-294] Argolla plata 925 lisa gancho anzuelo 1cm", precio: 6.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_15.jpg', nombre: "Aretes Topo aros", desc: "[P-AR-562] Topo plata 925 aros", precio: 5.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_16.jpg', nombre: "Aretes Topo medialunas", desc: "[P-AR-560] Topo plata 925 mini medialunas", precio: 5.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_17.jpg', nombre: "Aretes Topo triángulos", desc: "[P-AR-559] Topo plata 925 triángulos troquelados", precio: 5.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_18.jpg', nombre: "Aretes Topo flechas", desc: "[P-AR-556] Topo plata 925 flechas", precio: 5.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_19.jpg', nombre: "Aretes Topo circón cuadrado", desc: "[P-AR-531] Topo plata ley 925 circón cuadrado blanco (7x7)", precio: 7.0, esPedido: true },
    { estado: 'agotado', img: 'aretes/arete_20.jpg', nombre: "Aretes Topo repulgue", desc: "[P-AR-262] Topo plata ley 925 circón cuadrado blanco (7x7)", precio: 7.0, esPedido: false },
    { estado: 'pedido', img: 'aretes/arete_21.jpg', nombre: "Aretes hello kitty", desc: "[P-AR-199] Aretes en Plata ley 925 hello kitty mini microcircón turquesa", precio: 7.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_22.jpg', nombre: "Aretes cerezas", desc: "[P-AR-192] Aretes en Plata ley 925 cerezas mini microcircón turquesa", precio: 9.20, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_23.jpg', nombre: "Aretes silueta corazón", desc: "[P-AR-205] Aretes en Plata ley 925 silueta corazón mini microcircón turquesa", precio: 9.20, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_24.jpg', nombre: "Aretes estrella", desc: "[P-AR-194] Aretes en Plata ley 925 estrella mini circón turquesa", precio: 9.20, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_25.jpg', nombre: "Argolla lisa N° 5", desc: "[P-AR-568] Argolla en plata ley 925 lisa 2 cm", precio: 9.20, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_26.jpg', nombre: "Aretes Totopo osos circones", desc: "[P-AR-566] Topo plata 925 osos con circones rosca de seguridad (ortopedico)", precio: 9.50, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_27.jpg', nombre: "Aretes Totopo tortugas esmaltadas", desc: "[P-AR-564] Topo plata 925 tortugas esmaltadas rosca de seguridad (ortopedico)", precio: 9.50, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_28.jpg', nombre: "Aretes Totopo margaritas esmaltadas", desc: "[P-AR-563] Topo plata 925 margaritas esmaltadas rosca de seguridad (ortopedico)", precio: 9.50, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_29.jpg', nombre: "Aretes Totopo pies", desc: "[P-AR-373] Topos en plata ley 925 pies rosca de seguridad (ortopedico)", precio: 9.50, esPedido: true },
    { estado: 'agotado', img: 'aretes/arete_30.jpg', nombre: "Argolla huggie N° 3", desc: "[P-AR-370] Argolla huggie plata ley 925 lisa 1 cm", precio: 7.0, esPedido: false },
    { estado: 'pedido', img: 'aretes/arete_31.jpg', nombre: "Aretes Topo cristal", desc: "[P-AR-248] Topo plata 925 cristal color redondo", precio: 7.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_32.jpg', nombre: "Aretes cuadrado", desc: "[P-AR-323] Arete plata 925 cuadrado 8mm", precio: 8.0, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_33.jpg', nombre: "Aretes Topo hoja palma", desc: "[P-AR-550] Topo plata 925 (b.rodio) hoja palma rosca de seguridad (ortopedico)", precio: 12.50, esPedido: true },
    { estado: 'pedido', img: 'aretes/arete_34.jpg', nombre: "Aretes Topo perla y triángulo", desc: "[P-AR-547] Topo plata 925 (b.rodio) perla y triángulo rosca de seguridad (ortopedico)", precio: 12.50, esPedido: true },
    { estado: 'agotado', img:'aretes/arete_35.jpg', nombre: "Aretes hojitas", desc: "[P-AR-504] Arete plata 925 rosca de seguridad (rodinado) hojitas", precio: 12.50, esPedido: false },

  ],

  // ── JUEGOS ──
  juegos: [
    { estado: 'disponible', img: 'juegos/juego_1.jpg', nombre: "Juego de plata cuadrado", desc: "[P-JU-212] Juego de plata ley 925 cuadrado cristales blancos", precio: 45.0, esPedido: false },
    { estado: 'disponible', img: 'juegos/juego_2.jpg', nombre: "Juego de plata mariposa", desc: "[P-JU-206] Juego de plata ley 925 mariposa micrones blancos", precio: 45.0, esPedido: false },
    { estado: 'pedido', img: 'juegos/juego_3.jpg', nombre: "Juego oro medalla", desc: "[P-JU-190] Juego en plata y oro medalla virgen microcircon color surtido", precio: 55.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_4.jpg', nombre: "Juego gota", desc: "[P-JU-181] Juego en plata ley 925 gota microcircones blancos", precio: 55.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_5.jpg', nombre: "Juego corazón llave", desc: "[P-JU-198] Juego en plata ley 925 corazón llave microcirconia", precio: 50.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_6.jpg', nombre: "Juego thai", desc: "[P-JU-118] Juego plata 925 thai broche catalan lazo cristal azul", precio: 50.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_7.jpg', nombre: "Juego media luna", desc: "[P-JU- 208] Juego en plata ley 925 media luna circón", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_8.jpg', nombre: "Juego unicornio", desc: "[P-JU- 197] Juego para niña en plata ley 925 unicornio", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_9.jpg', nombre: "Juego thai flor", desc: "[P-JU- 187] Juego en plata ley 925 thai flor circón rojo", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_10.jpg', nombre: "Juego especial 15", desc: "[P-JU- 146] Juego plata 925 especial joya corazón quince años", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'juegos/juego_11.jpg', nombre: "Juego ositos", desc: "[P-JU- 102] Juego plata 925 ositos circones", precio: 45.0, esPedido: true },
  ],

  // ── DIJES ──
  dijes: [
    { estado: 'disponible', img: 'dijes/dije_1.jpg', nombre: "Dije estrella", desc: "[P-DJ|- 224] Dije plata ley 925 estrella", precio: 7.0, esPedido: false },
    { estado: 'disponible', img: 'dijes/dije_2.jpg', nombre: "Dije mariposa", desc: "[P-DJ-181] Dije plata ley 925 mariposa", precio: 7.0, esPedido: false },
    { estado: 'pedido', img: 'dijes/dije_3.jpg', nombre: "Dije medalla", desc: "[P-DJ-248] Dije en plata ley 925 medalla especial enjoyada", precio: 35.0, esPedido: true },
    { estado: 'disponible', img: 'dijes/dije_4.jpg', nombre: "Dije cruz", desc: "[P-DJ-141] Dije plata 925 cruz puntas cristo 1.8 cm", precio: 7.0, esPedido: false },
    { estado: 'pedido', img: 'dijes/dije_5.jpg', nombre: "Dije inicial", desc: "[P-DJ-208] Dije en plata ley 925 inicial - letras: b-e-f-h-l-o-s-t-v-w-x-y", precio: 10.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_6.jpg', nombre: "Dije inicial redonda", desc: "[P-DJ-207] Dije en plata ley 925 dije inicial redonda - letras: i - m - r - x", precio: 10.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_7.jpg', nombre: "Dije inicial cursiva", desc: "[P-DJ-206] Dije en plata ley 925 letra inicial cursiva - letra m", precio: 10.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_8.jpg', nombre: "Dije familia", desc: "[P-DJ-364] Dije en plata ley 925 familia", precio: 12.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_9.jpg', nombre: "Dije corazón", desc: "[P-DJ-146] Dije plata 925 corazón delfines", precio: 7.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_10.jpg', nombre: "Dije búho", desc: "[P-DJ-219] Dije en plata ley 925 búho modelo 2", precio: 7.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_11.jpg', nombre: "Dije estrella", desc: "[P-DJ-366] Dije en plata ley 925 estrella de david", precio: 7.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_12.jpg', nombre: "Dije herradura", desc: "[P-DJ-139] Dije plata ley 925 herradura caballo 2 cm", precio: 10.0, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_13.jpg', nombre: "Dije guitarra", desc: "[P-DJ-228] Dije en plata ley 925 guitarra", precio: 10.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_14.jpg', nombre: "Dije pantera", desc: "[P-DJ-251] Dije en plata ley 925 pantera microcircones", precio: 12.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_15.jpg', nombre: "Dije búho", desc: "[P-DJ-362] Dije en plata ley 925 búho", precio: 14.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_16.jpg', nombre: "Dije herradura", desc: "[P-DJ-359] Dije en plata ley 925 herradura", precio: 12.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_17.jpg', nombre: "Dije aguila", desc: "[P-DJ-213] Dije en plata ley 925 aguila", precio: 14.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_18.jpg', nombre: "Dije corazón", desc: "[P-DJ-361] Dije en plata ley 925 corazón soplado", precio: 15.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_19.jpg', nombre: "Dije manito", desc: "[P-DJ-230] Dije en plata ley 925 manito microcircones", precio: 15.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_20.jpg', nombre: "Dije enjoyado N° 1", desc: "[P-DJ-250] Dije en plata ley 925 enjoyado libélula", precio: 16.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_21.jpg', nombre: "Dije enjoyado N° 2", desc: "[P-DJ-155] Dije plata ley 925 enjoyado ojito color surtido", precio: 17.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_22.jpg', nombre: "Dije manito", desc: "[P-DJ-356] Dije en plata ley 925 manito hamsa", precio: 17.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_23.jpg', nombre: "Dije colibrí", desc: "[P-DJ-349] Dije en plata ley 925 colibrí", precio: 17.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_24.jpg', nombre: "Dije corazón", desc: "[P-DJ-236] Dije en plata ley 925 corazón grande martillado", precio: 18.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_25.jpg', nombre: "Dije enjoyado N° 3", desc: "[P-DJ-159] Dije plata ley 925 enjoyado mano hamsa color surtido", precio: 18.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_26.jpg', nombre: "Dije manito", desc: "[P-DJ-130] Dije en plata ley 925 manito hansa circionia lila", precio: 18.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_27.jpg', nombre: "Dije música", desc: "[P-DJ-344] Dije en plata ley 925 música", precio: 19.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_28.jpg', nombre: "Dije kit medicina", desc: "[P-DJ-345] Dije en plata ley 925 kit medicina", precio: 20.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_29.jpg', nombre: "Dije moto", desc: "[P-DJ-354] Dije en plata ley 925 kit moto", precio: 22.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_30.jpg', nombre: "Dije cruz", desc: "[P-DJ-237] Dije en plata ley 925 cruz cristo 5cm", precio: 23.5, esPedido: true },
    { estado: 'pedido', img: 'dijes/dije_31.jpg', nombre: "Dije enjoyado N° 4", desc: "[P-DJ-173] Dije plata ley 925 enjoyado cruz microcircones negros 4cm", precio: 28.5, esPedido: true },
  ],

  // ── CADENAS ──
  cadenas: [
    { estado: 'disponible', img: 'cadenas/cadena_2.jpg', nombre: "Cadena barbada", desc: "[P-CD-177] Cadena plata ley 925 de 45cm, tejido barbada extra fina.", precio: 20.0, esPedido: false },
    { estado: 'disponible', img: 'cadenas/cadena_1.jpg', nombre: "Cadena tejido veneciana", desc: "[P-CD-138] Cadena plata 925 tejido veneciana 45cm.", precio: 35.0, esPedido: false },
    { estado: 'disponible', img: 'cadenas/cadena_3.jpg', nombre: "Cadena tejido marinero", desc: "[P-CD-183] Cadena en plata ley 925 tejido marinero 60 cm", precio: 35.0, esPedido: false },
    { estado: 'pedido', img: 'cadenas/cadena_4.jpg', nombre: "Cadena tejido bilbao", desc: "[P-CD-103] Cadena plata 925 tejido bilbao 45 cm", precio: 12.5, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_5.jpg', nombre: "Cadena tejido cartier", desc: "[P-CD- 176] Cadena plata 925 tejido bilbao 45 cm", precio: 19.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_6.jpg', nombre: "Cadena tejido forzada", desc: "[P-CD-105] Cadena plata 925 tejido forzada 45cm", precio: 19.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_7.jpg', nombre: "Cadena tejido  plano", desc: "[P-CD-178] Cadena en plata ley 925 tejido plano diamantada 45 cm", precio: 19.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_8.jpg', nombre: "Cadena tejido  plano marinero", desc: "[P-CD-179] Cadena en plata ley 925 tejido plano marinero diamantada 50 cm", precio: 24.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_9.jpg', nombre: "Cadena tejido cordón", desc: "[P-CD-141] Cadena plata 925 tejido cordón 45 cm.", precio: 24.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_10.jpg', nombre: "Cadena tejido forzada", desc: "[P-CD-108] Cadena plata 925 tejido forzada 45cm modelo 2.", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_11.jpg', nombre: "Cadena tejido valentino / marinero", desc: "[P-CD-182] Cadena en plata ley 925 tejido valentino / marinero 45 cm.", precio: 34.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_12.jpg', nombre: "Cadena rolo", desc: "[P-CD-139] Cadena plata 925 rolo 45 cm.", precio: 34.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_13.jpg', nombre: "Cadena plano", desc: "[P-CD-133] Cadena plata 925 tejido plano 5mm 65 cm.", precio: 90.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_14.jpg', nombre: "Cadena tejido forzada gruesa", desc: "[P-CD-135] Cadena en plata ley 925 tejido forzada gruesa 50 cm.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_15.jpg', nombre: "Cadena tejido plano", desc: "[P-CD-166] Cadena plata ley tejido plano 2.5mm x 60cm.", precio: 40.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_16.jpg', nombre: "Cadena tejido valentino", desc: "[P-CD-167] Cadena plata ley 925 tejido valentino 3mm x 60cm.", precio: 42.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_17.jpg', nombre: "Cadena tejido barbada", desc: "[P-CD-160] Cadena plata 925 tejido barbada 50cm 4mm.", precio: 77.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_18.jpg', nombre: "Cadena tejido plano", desc: "[P-CD-122] Cadena plata 925 tejido plano 5mm 55 cm.", precio: 80.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_19.jpg', nombre: "Cadena tejido cordón", desc: "[P-CD-171] Cadena plata ley 925 tejido cordón 2.5mm x60cm.", precio: 80.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas/cadena_20.jpg', nombre: "Cadena tejido cartier", desc: "[P-CD-172] Cadena plata ley 925 tejido cartier 7 escalera 4mm x 60cm.", precio: 90.0, esPedido: true },
  ],

  // ── CADENAS CON DIJES ──
  cadenas_dijes: [
    { estado: 'disponible', img: 'cadenas_dijes/cadena_dije_1.jpg', nombre: "Cadena con Dije corazón", desc: "Cadena con dije plata ley 925 de corazon con circón rojo.", precio: 25.0, esPedido: false },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_2.jpg', nombre: "Cadena con dije perla", desc: "[P-CDD-223] Cadena con dije perla solitario gold plata 925.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_3.jpg', nombre: "Cadena con dije cubo", desc: "[P-CDD-221] Cadena con dije cubo cristal gold plata 925.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_4.jpg', nombre: "Cadena con dije cilindro", desc: "[P-CDD-221] Cadena con dije cilindro plata 925.", precio: 15.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_5.jpg', nombre: "Cadena con dije inicial", desc: "[P-CDD-152] Collar en plata ley 925 dije inicial microcircones 9 mm \"R-Z-W-S-D-T-I-F-A-P-K-N-G-O-H-J-B-Y-V-U-X-E-M-L-C\".", precio: 17.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_6.jpg', nombre: "Cadena con dije inicial", desc: "[P-CDD-128] Collar en plata ley 925 dije inicial microcircones 1.2 cm \"B-J-I-N-S-V-K-R-G-Y-P-L-M-F-Z-T\".", precio: 17.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_7.jpg', nombre: "Cadena con dije huellitas", desc: "[P-CDD-232] Collar en plata ley 925 huellitas microcircones blancos.", precio: 18.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_8.jpg', nombre: "Cadena con dije rombo", desc: "[P-CDD-262] Collar en plata ley 925 baño en oro rosa rombo.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_9.jpg', nombre: "Cadena con dije harry potter", desc: "[P-CDD-179] Collar plata 925 baño rodio tono rosa harry potter.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_10.jpg', nombre: "Cadena con dije punto de luz", desc: "[P-CDD-178] Collar plata 925 baño rodio tono rosa circón punto de luz.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_11.jpg', nombre: "Cadena con dije círculo", desc: "[P-CDD-175] Collar plata 925 baño rodio dorado círculo microcircones blancos.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_12.jpg', nombre: "Cadena con dije pez", desc: "[P-CDD-172] Collar plata 925 baño rodio dorado pez perlitas.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_13.jpg', nombre: "Cadena con dije saturno", desc: "[P-CDD-170] Collar plata 925 baño rodio llave saturno ópalo.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_14.jpg', nombre: "Cadena con dije luna saturno", desc: "[P-CDD-168] Collar plata 925 baño rodio media luna saturno ópalo.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_15.jpg', nombre: "Cadena con dije látido", desc: "[P-CDD-166] Collar plata 925 baño rodio látido corazón.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_16.jpg', nombre: "Cadena con dije hojita", desc: "[P-CDD-250] Collar en plata ley 925 dije hojita.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_17.jpg', nombre: "Cadena con dije círculo N° 1", desc: "[P-CDD-245] Collar plata 925 baño rodio círculo cristales.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_18.jpg', nombre: "Cadena con dije doble círculo", desc: "[P-CDD-253] Collar en plata ley 925 baño oro gold rose doble círculo.", precio: 23.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_19.jpg', nombre: "Cadena con dije círculo N° 2", desc: "[P-CDD-255] Collar en plata ley 925 círculo microcircones.", precio: 26.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_20.jpg', nombre: "Cadena con dije círculo nácar", desc: "[P-CDD-256] Collar en plata ley 925 círculo nácar.", precio: 26.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_21.jpg', nombre: "Cadena con dije cuarzo", desc: "[P-CDD-244] Collar en plata ley 925 cuarzo natural.", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_22.jpg', nombre: "Cadena con dije cruces", desc: "[P-CDD-235] Collar en plata ley 925 dijes cruces.", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_23.jpg', nombre: "Cadena con dije mariposa", desc: "[P-CDD-233] Collar en plata ley 925 mariposa microcircones blancos.", precio: 28.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_24.jpg', nombre: "Cadena con dije mariposas N° 1", desc: "[P-CDD-238] Collar en plata ley 925 dijes mariposa modelo 2.", precio: 30.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_25.jpg', nombre: "Cadena con dije mariposas N° 2", desc: "[P-CDD-239] Collar en plata ley 925 dijes mariposa.", precio: 30.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_26.jpg', nombre: "Cadena con dije círculo sol", desc: "[P-CDD-237] Collar en plata ley 925 círculo sol.", precio: 30.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_27.jpg', nombre: "Cadena con dije van cleef", desc: "[P-CDD-236] Collar en plata ley 925 dijes van cleef.", precio: 35.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_28.jpg', nombre: "Cadena con dije doble círculos", desc: "[P-CDD-110] Collar en plata ley 925 doble círculos cristales.", precio: 32.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_29.jpg', nombre: "Cadena con dije corazones", desc: "[P-CDD-109] Collar en plata ley 925 doble corazones.", precio: 32.0, esPedido: true },
    { estado: 'pedido', img: 'cadenas_dijes/cadena_dije_30.jpg', nombre: "Cadena con van cleef", desc: "[P-CDD-114] Collar en plata ley 925 van cleef negro.", precio: 35.0, esPedido: true },
  ],

};
